# Generated by Django 4.1.1 on 2022-10-03 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_bookmark_like_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='content_id',
            new_name='feed_id',
        ),
    ]
