# Generated by Django 4.1.1 on 2022-10-03 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_rename_content_id_reply_feed_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
