# Generated by Django 4.1.1 on 2022-10-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_bookmark_like_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='like_count',
        ),
    ]
